## Aggregation

In [1]:
list1=[1,2,3]
type(list1)

list

In [2]:
sum(list1)

6

In [3]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
sum(a)

6

In [5]:
np.sum(a)

6

## Creating a massive Numpy array

In [7]:
massive_array=np.random.random(1000)
massive_array

array([4.79721984e-01, 7.22784862e-01, 2.01233560e-01, 7.41614371e-01,
       3.19030178e-01, 8.42277402e-01, 6.08617328e-01, 1.76813036e-01,
       1.06182403e-01, 1.79398302e-01, 3.23146283e-01, 8.94973453e-01,
       7.09772765e-01, 1.70500112e-01, 5.33741579e-01, 7.88042763e-01,
       6.99610328e-01, 9.86501131e-01, 3.81863637e-01, 3.79775834e-01,
       8.20931312e-01, 2.79265283e-01, 7.45431000e-01, 1.50227876e-01,
       7.00409991e-01, 7.11372565e-01, 7.68152026e-01, 7.59373895e-01,
       1.67315440e-01, 8.57599474e-01, 9.09467287e-03, 2.16168249e-01,
       3.90598095e-01, 5.52897496e-01, 9.25244458e-01, 7.77159901e-01,
       3.60397609e-01, 1.45870573e-01, 2.21669649e-01, 8.91969341e-01,
       2.49486030e-01, 7.23490986e-01, 6.50005394e-01, 4.46300352e-01,
       3.42241594e-01, 4.84129855e-01, 6.44277906e-01, 7.19964615e-01,
       5.18138548e-01, 9.84287841e-01, 6.02346588e-01, 5.96960828e-01,
       6.57727793e-01, 4.89870742e-01, 1.25367075e-01, 8.73084280e-01,
      

In [8]:
massive_array[:10]

array([0.47972198, 0.72278486, 0.20123356, 0.74161437, 0.31903018,
       0.8422774 , 0.60861733, 0.17681304, 0.1061824 , 0.1793983 ])

In [10]:
%timeit sum(massive_array)  #timeit-how loong a particular line of code takes to run. python's sum
%timeit np.sum(massive_array)    #numpy's sum

131 µs ± 3.78 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
7.69 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
np.var(a)

0.6666666666666666

In [12]:
np.std(a)

0.816496580927726

In [13]:
np.min(a)

1

In [14]:
np.mean(a)

2.0

In [16]:
np.max(a)

3

In [17]:
np.sqrt(np.var(a))

0.816496580927726