## Creating numpy arrays

In [2]:
import numpy as np
ones=np.ones((2,3))

In [3]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
ones.dtype

dtype('float64')

In [5]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])