## Comparison Operator

In [2]:
import numpy as np
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[2,3,4],
             [4,5,6]])
a2

array([[2, 3, 4],
       [4, 5, 6]])

In [4]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [5]:
a1<a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [6]:
a1>=a2

array([[False, False, False],
       [False, False, False]])

In [7]:
bool_array= a1>=a2
bool_array

array([[False, False, False],
       [False, False, False]])

In [9]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))