## Creating array 2

In [12]:
import numpy as np
np.random.seed(seed=20)
random_array=np.random.randint(0,10, size=(3,2))
random_array

array([[3, 9],
       [4, 6],
       [7, 2]])

In [9]:
random_array.size

6

In [10]:
random_array2=np.random.random((3,5))
random_array2

array([[0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [14]:
np.random.seed(7)
random_arr5=np.random.random((5,3))
random_arr5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])