## Datatypes  And Attributes

In [3]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7])
ar

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(ar)

numpy.ndarray

In [5]:
ar2=np.array([[1,2.0,3.5],
             [4, 5.5, 6]])
ar2

array([[1. , 2. , 3.5],
       [4. , 5.5, 6. ]])

In [6]:
ar3=np.array([[1,2.0,3.5],
             [4, 5.5, 6],
             [8.7, 6,9]])
ar3

array([[1. , 2. , 3.5],
       [4. , 5.5, 6. ],
       [8.7, 6. , 9. ]])

In [7]:
ar.shape

(7,)

In [8]:
ar2.shape

(2, 3)

In [9]:
ar3.shape

(3, 3)

In [11]:
ar.ndim, ar2.ndim, ar3.ndim

(1, 2, 2)

In [13]:
ar.dtype, ar2.dtype, ar3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [14]:
ar.size, ar2.size, ar3.size

(7, 6, 9)

In [15]:
type(ar), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

##creating DataFrame from Numpy array

In [16]:
import pandas as pd
df=pd.DataFrame(ar2)
df

0    1    2
0  1.0  2.0  3.5
1  4.0  5.5  6.0

In [17]:
df2=pd.DataFrame(ar3)
df2

0    1    2
0  1.0  2.0  3.5
1  4.0  5.5  6.0
2  8.7  6.0  9.0