## Manipulating and comparing arrays

## Arithemetic

In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[1,2],
            [3,4]])
b

array([[1, 2],
       [3, 4]])

In [4]:
c=np.array([[2,3,4],
            [5,6,7], 
            [7,8,9]])
c

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [9]:
ones=np.ones(4)
ones

array([1., 1., 1., 1.])

In [8]:
a 

array([1, 2, 3, 4])

In [10]:
a + ones

array([2., 3., 4., 5.])

In [11]:
a - ones

array([0., 1., 2., 3.])

In [12]:
a * ones

array([1., 2., 3., 4.])

In [13]:
a / ones

array([1., 2., 3., 4.])

In [18]:
b %2

array([[1, 0],
       [1, 0]], dtype=int32)