## Reshaping and transposing

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[2,3],
            [3,4]])
c=np.array([[1,2,3],
            [3,4,5],
            [5,6,7]])
a
b
c

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [5]:
b.shape

(2, 2)

In [6]:
b.reshape(2,2,1)

array([[[2],
        [3]],

       [[3],
        [4]]])

In [7]:
c.shape

(3, 3)

In [8]:
c.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[3],
        [4],
        [5]],

       [[5],
        [6],
        [7]]])