## Sorting arrays

In [1]:
import numpy as np
random_arr=np.random.randint(10, size=(3,5))

In [2]:
random_arr

array([[9, 0, 7, 0, 5],
       [8, 0, 2, 7, 9],
       [5, 4, 5, 3, 5]])

In [3]:
np.sort(random_arr)

array([[0, 0, 5, 7, 9],
       [0, 2, 7, 8, 9],
       [3, 4, 5, 5, 5]])

In [4]:
np.argsort(random_arr)

array([[1, 3, 4, 2, 0],
       [1, 2, 3, 0, 4],
       [3, 1, 0, 2, 4]], dtype=int64)

In [5]:
np.argmin(random_arr)

1

In [7]:
np.argmax(random_arr, axis=0)

array([0, 2, 0, 1, 1], dtype=int64)