## Viewing arrays and Matrices

In [3]:
import numpy as np
random_array=np.random.randint(10, size=(3,2))
random_array

array([[1, 6],
       [5, 6],
       [2, 3]])

In [4]:
np.unique(random_array)

array([1, 2, 3, 5, 6])

In [6]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
a2=np.array([[2,3],
             [4,5]])
a2

array([[2, 3],
       [4, 5]])

In [8]:
a3=np.array([[3,4,5],
             [2,6,8],
             [1,4,5]])
a3

array([[3, 4, 5],
       [2, 6, 8],
       [1, 4, 5]])

## viewing the element

In [9]:
a1[0]

1

In [11]:
a2[0][1]

3

In [12]:
a3[1][2]

8

In [13]:
a3.shape

(3, 3)

In [14]:
a3

array([[3, 4, 5],
       [2, 6, 8],
       [1, 4, 5]])

In [17]:
a3[:2, :2]

array([[3, 4],
       [2, 6]])

In [18]:
a4=np.random.randint(10, size=(2,3,4,5))
a4

array([[[[7, 6, 4, 7, 7],
         [7, 3, 1, 3, 2],
         [5, 4, 9, 1, 7],
         [2, 1, 9, 2, 6]],

        [[5, 7, 8, 0, 2],
         [3, 2, 4, 3, 4],
         [5, 6, 2, 1, 5],
         [1, 1, 3, 2, 0]],

        [[3, 4, 4, 3, 4],
         [6, 9, 0, 9, 9],
         [3, 4, 1, 5, 5],
         [3, 6, 3, 9, 6]]],


       [[[4, 8, 8, 9, 0],
         [2, 3, 0, 6, 9],
         [4, 0, 3, 6, 9],
         [8, 5, 7, 7, 7]],

        [[9, 7, 1, 7, 1],
         [5, 8, 4, 8, 4],
         [5, 8, 7, 0, 5],
         [9, 4, 7, 9, 7]],

        [[6, 0, 4, 8, 5],
         [7, 7, 1, 5, 5],
         [8, 7, 7, 3, 3],
         [6, 4, 6, 4, 6]]]])

In [19]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

## Get the 4 first elements in the innermost array

In [20]:
a4[:,:,:,:4]

array([[[[7, 6, 4, 7],
         [7, 3, 1, 3],
         [5, 4, 9, 1],
         [2, 1, 9, 2]],

        [[5, 7, 8, 0],
         [3, 2, 4, 3],
         [5, 6, 2, 1],
         [1, 1, 3, 2]],

        [[3, 4, 4, 3],
         [6, 9, 0, 9],
         [3, 4, 1, 5],
         [3, 6, 3, 9]]],


       [[[4, 8, 8, 9],
         [2, 3, 0, 6],
         [4, 0, 3, 6],
         [8, 5, 7, 7]],

        [[9, 7, 1, 7],
         [5, 8, 4, 8],
         [5, 8, 7, 0],
         [9, 4, 7, 9]],

        [[6, 0, 4, 8],
         [7, 7, 1, 5],
         [8, 7, 7, 3],
         [6, 4, 6, 4]]]])

In [21]:
a4[:, :, :, :2]

array([[[[7, 6],
         [7, 3],
         [5, 4],
         [2, 1]],

        [[5, 7],
         [3, 2],
         [5, 6],
         [1, 1]],

        [[3, 4],
         [6, 9],
         [3, 4],
         [3, 6]]],


       [[[4, 8],
         [2, 3],
         [4, 0],
         [8, 5]],

        [[9, 7],
         [5, 8],
         [5, 8],
         [9, 4]],

        [[6, 0],
         [7, 7],
         [8, 7],
         [6, 4]]]])